name: Build and Push Kali Linux Docker Image

on:
  push:
    branches:
      - main  # Trigger build when pushing to the 'main' branch (you can change this to 'master' or any branch you prefer)
  pull_request:
    branches:
      - main  # Trigger build when a PR is created/updated for the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for the build

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Use your Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Use your Docker Hub password or access token

    # Step 3: Set up Docker Buildx for multi-platform builds (optional)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t codepromax24/kalilinux:latest .

    # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push codepromax24/kalilinux:latest
